/**
 * generator.ts — Generates code for new capabilities.
 *
 * Each capability type has a template that produces a standalone file.
 * Generated files are placed in ~/.open-coleslaw/custom-{type}s/.
 */

import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { getConfig } from '../utils/config.js';
import type { CapabilityType, Capability } from './capability-registry.js';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface GenerateRequest {
  type: CapabilityType;
  name: string;
  description: string;
  trigger: string;
  userRequest: string;
}

export interface GenerateResult {
  filePath: string;
  code: string;
  registryEntry: Omit<Capability, 'createdAt'>;
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function sanitizeName(name: string): string {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

function header(request: GenerateRequest): string {
  const now = new Date().toISOString();
  return [
    `// Auto-generated by open-coleslaw extension system`,
    `// Name: ${request.name}`,
    `// Description: ${request.description}`,
    `// Trigger: ${request.trigger}`,
    `// Created: ${now}`,
    '',
  ].join('\n');
}

function customDir(type: CapabilityType): string {
  const { DATA_DIR } = getConfig();
  const dir = join(DATA_DIR, `custom-${type}s`);
  mkdirSync(dir, { recursive: true });
  return dir;
}

// ---------------------------------------------------------------------------
// Templates per capability type
// ---------------------------------------------------------------------------

function generateHook(request: GenerateRequest): string {
  return [
    header(request),
    `/**`,
    ` * Custom hook: ${request.name}`,
    ` * ${request.description}`,
    ` *`,
    ` * Trigger: ${request.trigger}`,
    ` * Original request: ${request.userRequest}`,
    ` *`,
    ` * Usage:`,
    ` *   node custom-hooks/${sanitizeName(request.name)}.js`,
    ` */`,
    ``,
    `function main() {`,
    `  // Read input from stdin or environment if needed`,
    `  const input = process.env.HOOK_INPUT ?? '';`,
    ``,
    `  // TODO: Implement hook logic for "${request.description}"`,
    `  const result = {`,
    `    hook: '${request.name}',`,
    `    status: 'executed',`,
    `    input,`,
    `    timestamp: new Date().toISOString(),`,
    `  };`,
    ``,
    `  process.stdout.write(JSON.stringify(result));`,
    `}`,
    ``,
    `main();`,
    ``,
  ].join('\n');
}

function generateSkill(request: GenerateRequest): string {
  return [
    header(request),
    `/**`,
    ` * Custom skill: ${request.name}`,
    ` * ${request.description}`,
    ` *`,
    ` * Trigger: ${request.trigger}`,
    ` * Original request: ${request.userRequest}`,
    ` */`,
    ``,
    `export function get${toPascalCase(request.name)}SkillPrompt(args) {`,
    `  const input = args?.trim() ?? '';`,
    ``,
    `  return [`,
    `    '<command-name>${request.name}</command-name>',`,
    `    '',`,
    `    '## ${request.name} Skill',`,
    `    '',`,
    `    '${request.description}',`,
    `    '',`,
    `    input ? \`User input: \${input}\` : 'No input provided.',`,
    `    '',`,
    `    'Instructions:',`,
    `    '1. Analyze the user request',`,
    `    '2. Perform the action described above',`,
    `    '3. Report the result to the user',`,
    `  ].join('\\n');`,
    `}`,
    ``,
  ].join('\n');
}

function generateCommand(request: GenerateRequest): string {
  return [
    header(request),
    `/**`,
    ` * Custom command: ${request.name}`,
    ` * ${request.description}`,
    ` *`,
    ` * Trigger: ${request.trigger}`,
    ` * Original request: ${request.userRequest}`,
    ` *`,
    ` * Usage:`,
    ` *   node custom-commands/${sanitizeName(request.name)}.js [action] [args...]`,
    ` */`,
    ``,
    `function main() {`,
    `  const args = process.argv.slice(2);`,
    `  const action = args[0] ?? 'default';`,
    `  const rest = args.slice(1);`,
    ``,
    `  const handlers = {`,
    `    default: () => ({`,
    `      command: '${request.name}',`,
    `      description: '${request.description}',`,
    `      usage: '${request.name}:action [args]',`,
    `    }),`,
    `    run: () => {`,
    `      // TODO: Implement the primary command action`,
    `      return {`,
    `        command: '${request.name}',`,
    `        action: 'run',`,
    `        args: rest,`,
    `        status: 'executed',`,
    `        timestamp: new Date().toISOString(),`,
    `      };`,
    `    },`,
    `  };`,
    ``,
    `  const handler = handlers[action] ?? handlers.default;`,
    `  const result = handler();`,
    `  process.stdout.write(JSON.stringify(result, null, 2));`,
    `}`,
    ``,
    `main();`,
    ``,
  ].join('\n');
}

function generateAsset(request: GenerateRequest): string {
  // Assets can be JSON or Markdown. Default to JSON for configs, Markdown for docs.
  const isMarkdown =
    /template|guide|doc|readme|note/i.test(request.name) ||
    /template|guide|doc|readme|note/i.test(request.description);

  if (isMarkdown) {
    return [
      `<!-- Auto-generated by open-coleslaw extension system -->`,
      `<!-- Name: ${request.name} -->`,
      `<!-- Description: ${request.description} -->`,
      `<!-- Trigger: ${request.trigger} -->`,
      `<!-- Created: ${new Date().toISOString()} -->`,
      ``,
      `# ${request.name}`,
      ``,
      `${request.description}`,
      ``,
      `## Details`,
      ``,
      `> Original request: ${request.userRequest}`,
      ``,
      `<!-- TODO: Fill in content -->`,
      ``,
    ].join('\n');
  }

  const data = {
    _meta: {
      generatedBy: 'open-coleslaw extension system',
      name: request.name,
      description: request.description,
      trigger: request.trigger,
      created: new Date().toISOString(),
      userRequest: request.userRequest,
    },
    config: {},
  };

  return JSON.stringify(data, null, 2) + '\n';
}

function generateLoop(request: GenerateRequest): string {
  return [
    header(request),
    `/**`,
    ` * Custom loop: ${request.name}`,
    ` * ${request.description}`,
    ` *`,
    ` * Trigger: ${request.trigger}`,
    ` * Original request: ${request.userRequest}`,
    ` *`,
    ` * Usage:`,
    ` *   node custom-loops/${sanitizeName(request.name)}.js`,
    ` */`,
    ``,
    `const INTERVAL_MS = 30000; // 30 seconds`,
    `const MAX_ITERATIONS = 100;`,
    ``,
    `async function check() {`,
    `  // TODO: Implement the condition check for "${request.description}"`,
    `  const result = {`,
    `    loop: '${request.name}',`,
    `    iteration: 0,`,
    `    timestamp: new Date().toISOString(),`,
    `    conditionMet: false,`,
    `  };`,
    `  return result;`,
    `}`,
    ``,
    `async function main() {`,
    `  let iteration = 0;`,
    ``,
    `  while (iteration < MAX_ITERATIONS) {`,
    `    iteration++;`,
    `    const result = await check();`,
    `    result.iteration = iteration;`,
    ``,
    `    process.stdout.write(JSON.stringify(result) + '\\n');`,
    ``,
    `    if (result.conditionMet) {`,
    `      process.stdout.write(JSON.stringify({`,
    `        loop: '${request.name}',`,
    `        status: 'completed',`,
    `        totalIterations: iteration,`,
    `      }) + '\\n');`,
    `      break;`,
    `    }`,
    ``,
    `    await new Promise((resolve) => setTimeout(resolve, INTERVAL_MS));`,
    `  }`,
    `}`,
    ``,
    `main().catch((err) => {`,
    `  process.stderr.write(String(err));`,
    `  process.exit(1);`,
    `});`,
    ``,
  ].join('\n');
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function toPascalCase(str: string): string {
  return str
    .split(/[-_\s]+/)
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
    .join('');
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Generate code for a new capability.
 *
 * Returns the file path where the code was written, the code itself,
 * and the registry entry to persist.
 */
export function generateCapability(request: GenerateRequest): GenerateResult {
  const safeName = sanitizeName(request.name);

  // Determine file extension based on type
  const isAssetMarkdown =
    request.type === 'asset' &&
    (/template|guide|doc|readme|note/i.test(request.name) ||
      /template|guide|doc|readme|note/i.test(request.description));

  let ext: string;
  if (request.type === 'asset') {
    ext = isAssetMarkdown ? '.md' : '.json';
  } else {
    ext = '.js';
  }

  const dir = customDir(request.type);
  const filePath = join(dir, `${safeName}${ext}`);

  // Generate the code
  let code: string;
  switch (request.type) {
    case 'hook':
      code = generateHook(request);
      break;
    case 'skill':
      code = generateSkill(request);
      break;
    case 'command':
      code = generateCommand(request);
      break;
    case 'asset':
      code = generateAsset(request);
      break;
    case 'loop':
      code = generateLoop(request);
      break;
  }

  // Write the file
  writeFileSync(filePath, code, 'utf-8');

  return {
    filePath,
    code,
    registryEntry: {
      type: request.type,
      name: request.name,
      description: request.description,
      trigger: request.trigger,
      isBuiltIn: false,
      filePath,
    },
  };
}
