/**
 * Plugin installer — /plugin install handler.
 *
 * Sets up the ~/.open-coleslaw/ directory structure, copies static assets,
 * and outputs the MCP server registration command.
 */

import { mkdirSync, writeFileSync, existsSync, readFileSync, copyFileSync } from 'node:fs';
import { homedir } from 'node:os';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

const DATA_DIR = join(homedir(), '.open-coleslaw');
const MINUTES_DIR = join(DATA_DIR, 'minutes');
const MINUTES_INDEX = join(MINUTES_DIR, 'INDEX.md');

const CUSTOM_DIRS = [
  'custom-hooks',
  'custom-skills',
  'custom-commands',
  'custom-assets',
  'custom-loops',
] as const;

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/**
 * Resolve the path to a bundled asset file.
 * When running from dist/, assets are expected at the package root src/assets/.
 * When running from source, they are at ../assets/ relative to this file.
 */
function resolveAssetPath(assetName: string): string {
  // __dirname equivalent for ESM
  const thisDir = dirname(fileURLToPath(import.meta.url));

  // Try common locations:
  // 1. Sibling assets/ directory (when compiled: dist/installer/ -> dist/assets/ is wrong,
  //    but the source layout is src/installer/ -> src/assets/)
  // 2. Up one level then assets/ (dist/installer/ -> src/assets/)
  const candidates = [
    join(thisDir, '..', 'assets', assetName),         // src/assets/ from src/installer/
    join(thisDir, 'assets', assetName),                // assets/ sibling
    join(thisDir, '..', '..', 'src', 'assets', assetName), // from dist/ back to src/
  ];

  for (const candidate of candidates) {
    if (existsSync(candidate)) {
      return candidate;
    }
  }

  // Fallback: return the first candidate (will fail gracefully at copy time)
  return candidates[0];
}

function ensureDir(dirPath: string): void {
  mkdirSync(dirPath, { recursive: true });
}

function copyAsset(assetName: string, destPath: string): boolean {
  const srcPath = resolveAssetPath(assetName);
  try {
    const content = readFileSync(srcPath, 'utf-8');
    writeFileSync(destPath, content, 'utf-8');
    return true;
  } catch {
    return false;
  }
}

// ---------------------------------------------------------------------------
// Minutes INDEX.md
// ---------------------------------------------------------------------------

const INDEX_TEMPLATE = `# Meeting Minutes Index

> Auto-generated by Open-Coleslaw. Do not edit manually.

| # | Date | Topic | Status | File |
|---|------|-------|--------|------|
`;

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Install the Open-Coleslaw plugin.
 *
 * Steps:
 * 1. Create ~/.open-coleslaw/ directory structure
 * 2. Copy rules.md, plugin-guide.md to ~/.open-coleslaw/
 * 3. Create minutes/INDEX.md
 * 4. Create custom-hooks/, custom-skills/, custom-commands/, custom-assets/, custom-loops/ dirs
 * 5. Output the MCP server registration command
 * 6. Return installation summary
 */
export async function installPlugin(): Promise<string> {
  const steps: string[] = [];
  const warnings: string[] = [];

  // 1. Create root data directory
  ensureDir(DATA_DIR);
  steps.push(`Created data directory: ${DATA_DIR}`);

  // 2. Create minutes directory
  ensureDir(MINUTES_DIR);
  steps.push(`Created minutes directory: ${MINUTES_DIR}`);

  // 3. Copy static assets
  const assetsCopied: string[] = [];

  if (copyAsset('rules.md', join(DATA_DIR, 'rules.md'))) {
    assetsCopied.push('rules.md');
  } else {
    warnings.push('Could not copy rules.md — asset file not found');
  }

  if (copyAsset('plugin-guide.md', join(DATA_DIR, 'plugin-guide.md'))) {
    assetsCopied.push('plugin-guide.md');
  } else {
    warnings.push('Could not copy plugin-guide.md — asset file not found');
  }

  if (assetsCopied.length > 0) {
    steps.push(`Copied assets: ${assetsCopied.join(', ')}`);
  }

  // 4. Create minutes INDEX.md (only if it doesn't exist)
  if (!existsSync(MINUTES_INDEX)) {
    writeFileSync(MINUTES_INDEX, INDEX_TEMPLATE, 'utf-8');
    steps.push('Created minutes/INDEX.md');
  } else {
    steps.push('minutes/INDEX.md already exists — skipped');
  }

  // 5. Create custom directories
  for (const dir of CUSTOM_DIRS) {
    const fullPath = join(DATA_DIR, dir);
    ensureDir(fullPath);
  }
  steps.push(`Created custom directories: ${CUSTOM_DIRS.join(', ')}`);

  // 6. MCP server registration command
  const mcpCommand = 'claude mcp add open-coleslaw -- npx open-coleslaw';

  // Build summary
  const lines: string[] = [
    '# Open-Coleslaw Installation Complete',
    '',
    '## Steps Performed',
    ...steps.map((s) => `- ${s}`),
    '',
  ];

  if (warnings.length > 0) {
    lines.push('## Warnings');
    lines.push(...warnings.map((w) => `- ${w}`));
    lines.push('');
  }

  lines.push(
    '## Register MCP Server',
    '',
    'Run the following command to register the MCP server with Claude Code:',
    '',
    '```bash',
    mcpCommand,
    '```',
    '',
    '## Directory Structure',
    '',
    '```',
    `${DATA_DIR}/`,
    '  rules.md              # Core rules (survives compaction)',
    '  plugin-guide.md       # Plugin usage guide',
    '  data.db               # SQLite database (created on first run)',
    '  minutes/',
    '    INDEX.md             # Auto-generated minutes index',
    '  custom-hooks/',
    '  custom-skills/',
    '  custom-commands/',
    '  custom-assets/',
    '  custom-loops/',
    '```',
    '',
    '## Next Steps',
    '',
    '1. Register the MCP server (command above)',
    '2. Restart Claude Code',
    '3. Try `/meeting [topic]` to start your first meeting',
  );

  return lines.join('\n');
}
