/**
 * doc-update hook — standalone script.
 *
 * After process completion, updates CLAUDE.md and README.md in the CWD
 * with project information gathered from the file system.
 *
 * - Checks if CLAUDE.md exists in CWD; creates or updates it with project info
 * - Checks if README.md exists; updates it
 * - Outputs the changes made to stdout
 *
 * Usage:
 *   node dist/hooks/doc-update.js [cwd]
 */

import { readFileSync, writeFileSync, existsSync, readdirSync, statSync } from 'node:fs';
import { resolve, join, basename } from 'node:path';

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function tryReadFile(filePath: string): string | null {
  try {
    return readFileSync(filePath, 'utf-8');
  } catch {
    return null;
  }
}

function tryReadJson(filePath: string): Record<string, unknown> | null {
  const raw = tryReadFile(filePath);
  if (!raw) return null;
  try {
    return JSON.parse(raw) as Record<string, unknown>;
  } catch {
    return null;
  }
}

function detectProjectType(cwd: string): { type: string; name: string; description: string } {
  // Check for package.json (Node/JS)
  const pkg = tryReadJson(join(cwd, 'package.json'));
  if (pkg) {
    return {
      type: 'node',
      name: (pkg['name'] as string) ?? basename(cwd),
      description: (pkg['description'] as string) ?? '',
    };
  }

  // Check for Cargo.toml (Rust)
  if (existsSync(join(cwd, 'Cargo.toml'))) {
    return { type: 'rust', name: basename(cwd), description: '' };
  }

  // Check for go.mod (Go)
  if (existsSync(join(cwd, 'go.mod'))) {
    return { type: 'go', name: basename(cwd), description: '' };
  }

  // Check for pyproject.toml or setup.py (Python)
  if (existsSync(join(cwd, 'pyproject.toml')) || existsSync(join(cwd, 'setup.py'))) {
    return { type: 'python', name: basename(cwd), description: '' };
  }

  return { type: 'unknown', name: basename(cwd), description: '' };
}

function listTopLevelStructure(cwd: string): string[] {
  try {
    return readdirSync(cwd)
      .filter((name) => !name.startsWith('.') && name !== 'node_modules' && name !== 'dist')
      .map((name) => {
        const full = join(cwd, name);
        try {
          const stat = statSync(full);
          return stat.isDirectory() ? `${name}/` : name;
        } catch {
          return name;
        }
      })
      .sort();
  } catch {
    return [];
  }
}

// ---------------------------------------------------------------------------
// CLAUDE.md generation
// ---------------------------------------------------------------------------

function generateClaudeMd(cwd: string, existing: string | null): string {
  const project = detectProjectType(cwd);
  const structure = listTopLevelStructure(cwd);

  const header = `# CLAUDE.md — ${project.name}`;
  const descLine = project.description
    ? `\n> ${project.description}\n`
    : '';

  const structureBlock = structure.length > 0
    ? `\n## Project Structure\n\n\`\`\`\n${structure.join('\n')}\n\`\`\`\n`
    : '';

  const typeInfo = `\n## Project Type\n\n- **Type**: ${project.type}\n- **Name**: ${project.name}\n`;

  // If existing content has user-added sections, preserve them
  let userSections = '';
  if (existing) {
    // Preserve anything after a "## Custom" or "## Notes" section
    const customIdx = existing.search(/^## (?!Project Structure|Project Type|Auto-generated)/m);
    if (customIdx > 0) {
      userSections = '\n' + existing.slice(customIdx);
    }
  }

  const footer = `\n---\n*Auto-generated by open-coleslaw doc-update hook. Last updated: ${new Date().toISOString().split('T')[0]}*\n`;

  return `${header}\n${descLine}${typeInfo}${structureBlock}${userSections}${footer}`;
}

// ---------------------------------------------------------------------------
// README.md update
// ---------------------------------------------------------------------------

function updateReadme(cwd: string, existing: string): string {
  const project = detectProjectType(cwd);

  // Only add an open-coleslaw badge/section if not already present
  const marker = '<!-- open-coleslaw -->';
  if (existing.includes(marker)) {
    // Already has our section — update the timestamp
    const updatedSection = buildReadmeSection(project.name);
    return existing.replace(
      /<!-- open-coleslaw -->[\s\S]*?<!-- \/open-coleslaw -->/,
      updatedSection,
    );
  }

  // Append our section at the end
  return existing.trimEnd() + '\n\n' + buildReadmeSection(project.name) + '\n';
}

function buildReadmeSection(projectName: string): string {
  const date = new Date().toISOString().split('T')[0];
  return [
    '<!-- open-coleslaw -->',
    `> Managed by [open-coleslaw](https://github.com/open-coleslaw) | Last sync: ${date}`,
    '<!-- /open-coleslaw -->',
  ].join('\n');
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

function main(): void {
  const cwd = process.argv[2] ? resolve(process.argv[2]) : process.cwd();
  const changes: string[] = [];

  // Verify the CWD exists
  if (!existsSync(cwd)) {
    process.stdout.write(`Directory does not exist: ${cwd}\n`);
    return;
  }

  // --- CLAUDE.md ---
  const claudeMdPath = join(cwd, 'CLAUDE.md');
  const existingClaude = tryReadFile(claudeMdPath);

  const newClaudeMd = generateClaudeMd(cwd, existingClaude);
  writeFileSync(claudeMdPath, newClaudeMd, 'utf-8');

  if (existingClaude) {
    changes.push(`Updated CLAUDE.md at ${claudeMdPath}`);
  } else {
    changes.push(`Created CLAUDE.md at ${claudeMdPath}`);
  }

  // --- README.md ---
  const readmeMdPath = join(cwd, 'README.md');
  const existingReadme = tryReadFile(readmeMdPath);

  if (existingReadme) {
    const newReadme = updateReadme(cwd, existingReadme);
    if (newReadme !== existingReadme) {
      writeFileSync(readmeMdPath, newReadme, 'utf-8');
      changes.push(`Updated README.md at ${readmeMdPath}`);
    } else {
      changes.push('README.md already up to date');
    }
  } else {
    changes.push('README.md does not exist — skipped');
  }

  // Output changes
  process.stdout.write(changes.join('\n') + '\n');
}

main();
